Add cookbook to expose Prometheus counters.
haskell-servant/servant pull request #1730
Opened 2024-03-17 13:02 UTC by lucasdicioccio

@tchoutri :kissing:

Not sure when I'll have time to address comments, so feel free to directly edit the PR.

The code itself is inspired from what I do in [prodapi](https://github.com/lucasdicioccio/prodapi/blob/master/prodapi/src/Prod/Prometheus.hs).

2024-03-18 20:28 UTC, lucasdicioccio reviewed
i blame myself

2024-03-18 20:28 UTC, lucasdicioccio commented on doc/cookbook/expose-prometheus/ExposePrometheus.lhs
> +of access to a feature when doing some A-B tests, the duration of database queriest to
typo queriest

2024-03-18 20:28 UTC, lucasdicioccio commented on doc/cookbook/expose-prometheus/ExposePrometheus.lhs
> +hitting rate-limits, the count the number of failed logins to report suspicious
typo the count the

2024-03-18 20:28 UTC, lucasdicioccio commented on doc/cookbook/expose-prometheus/ExposePrometheus.lhs
> +technologies to expose such _metrics_ and _traces_ about internals of services.
s/to .. /concerned with exposing

2024-03-18 20:28 UTC, lucasdicioccio commented on doc/cookbook/expose-prometheus/ExposePrometheus.lhs
> +values counted in background-thread, here, a counter in a sleep-loop.  Such
typo: in a

2024-03-18 20:28 UTC, lucasdicioccio commented on doc/cookbook/expose-prometheus/ExposePrometheus.lhs
> +text-formatted payload. Thus, our `Metrics` object contains the raw payload.
+ say exportMetricsAsText is an IO object, which we need to evaluate before rendering

2024-04-05 06:09 UTC, lucasdicioccio commented
@tchoutri any comment?

2024-04-05 09:46 UTC, tchoutri requested changes
Okay, quite a big review, I can understand if you'd rather let me handle it. :)

2024-04-05 09:46 UTC, tchoutri commented on doc/cookbook/expose-prometheus/ExposePrometheus.lhs
> +  mimeRender _ = toLBS
```suggestion
  mimeRender _ = getMetrics
```

2024-04-05 09:46 UTC, tchoutri commented on doc/cookbook/expose-prometheus/ExposePrometheus.lhs
> +For development and troubleshooting purpose, I only use my [own monitor tool](https://dicioccio.fr/prometheus-monitor.html) also available as [Firefox extension](https://addons.mozilla.org/en-GB/fire
```suggestion
For development and troubleshooting purpose, you can use [prometheus-monitor](https://dicioccio.fr/prometheus-monitor.html) also available as [Firefox extension](https://addons.mozilla.org/en-GB/firefox/addon/prometheus-monitor/).
```

2024-04-05 10:20 UTC, lucasdicioccio commented on doc/cookbook/expose-prometheus/ExposePrometheus.lhs
> +newtype Metrics = Metrics {toLBS :: ByteString}
maybe `FormattedMetrics` then so that `getMetrics` becomes `getFormattedMetrics` (if you want to have more explicit types)

2024-04-05 10:21 UTC, lucasdicioccio commented on doc/cookbook/expose-prometheus/ExposePrometheus.lhs
> +incrementing a counter every second.
correct, it's lazy writing

2024-04-05 10:26 UTC, lucasdicioccio commented on doc/cookbook/expose-prometheus/ExposePrometheus.lhs
> +incrementing a counter every second.
Maybe `We further instrument our program with a second metrics. This second metrics consist of a simple counter. A background thread will increment the counter every second`.

2024-04-05 10:27 UTC, tchoutri commented on doc/cookbook/expose-prometheus/ExposePrometheus.lhs
> +incrementing a counter every second.
yep!

2024-04-05 10:35 UTC, tchoutri commented on doc/cookbook/expose-prometheus/ExposePrometheus.lhs
> +newtype Metrics = Metrics {toLBS :: ByteString}
Yeah sure let's go!

2024-04-05 10:41 UTC, lucasdicioccio commented
> Any reason why you didn't use https://hackage.haskell.org/package/wai-middleware-prometheus for the WAI integration? I'm asking since it's part of the same family of packages as `wai-middleware-prometheus`.

Two things.
- (a) the cost of "writing your own" is low enough (as demonstrated in this example) vs. bundling "an extra dependency"
- (b) sometimes you would really benefit from parametrizing the metrics sets via query-params (e.g., to reduce network load), which is not feasible with the above package).

I haven't discussed (a), which is more of a taste/personal-experience judgment but we could add a mention as well (and maybe link to another cookbook to embed a middleware/serve a Raw Application).
For (b) it's a bit motivated in the writing, adding a filtering query-param in prodapi is low on my priority list but it's quite often that I wish I had a way to reduce the prometheus payload at the server-side.

2024-04-05 10:43 UTC, tchoutri commented
@lucasdicioccio cool, thanks for the explanation. :)

2025-01-23 13:22 UTC, tchoutri commented
@lucasdicioccio Hi! Could you please rebase your PR on current `master`? This will trigger a build of the cookbook. :)

2025-01-28 08:30 UTC, lucasdicioccio commented
@tchoutri do you mind if I squash the diffs?

2025-02-04 16:06 UTC, lucasdicioccio commented on doc/cookbook/expose-prometheus/ExposePrometheus.lhs
> +incrementing a counter every second.
done

2025-02-04 16:07 UTC, lucasdicioccio commented
> @lucasdicioccio Hi! Could you please rebase your PR on current `master`? This will trigger a build of the cookbook. :)

done; I've yet to retry the whole example, sorry for the delays

2025-02-05 14:42 UTC, tchoutri commented
@lucasdicioccio thanks! I and others will take a look. :)

2025-02-13 23:03 UTC, lucasdicioccio commented
> @lucasdicioccio thanks! I and others will take a look. :)

if you need some changes let me know as I have a small window of opportunity opening

2025-02-14 13:40 UTC, tchoutri commented
cc @Siprj

2025-02-17 12:11 UTC, Siprj commented
I like it. It is very useful to have a guide for making services more observable/resiliant :tada:.

2025-02-17 12:13 UTC, tchoutri requested changes
Can you add the cookbook to the [`cabal.project`](https://github.com/haskell-servant/servant/blob/master/cabal.project#L31) file?

2025-06-22 10:30 UTC, tchoutri approved these changes

2025-06-22 19:04 UTC, merged