Add `MkHandler` pattern synonym
haskell-servant/servant pull request #1733
Opened 2024-04-20 08:30 UTC by danidiaz

This bidirectional pattern synonym makes it easier to build `Handler a` values from `IO (Either ServerError a)` values, and is a complement to the already existing `runHandler` function.

![image](https://github.com/haskell-servant/servant/assets/1136927/5f786fff-d8a7-4b28-b62e-a9af3cd638b6)

As an alternative to this, I also considered re-exporting the `ExceptT` constructor, but I think it's better to have an explicit pattern synonym. `ExceptT` is not exactly an internal implementation detail, but it's sufficiently close to being one.

As for naming the pattern synonym, I considered `HandlerT` but it would be a bit misleading because `Handler` is not really a monad transformer. The prefix is `Mk` instead of `Make` because other parts of the Servant ecosystem (like safe links) have already settled on `Mk`.

Solves #1732.

2024-04-21 22:31 UTC, ysangkok commented
I think this is a breaking change per PVP, not sure if we are still making changelog.d entries or not. Another maintainer might want to weigh in.

2024-04-22 05:54 UTC, tchoutri commented
Yes please produce a changelog.d entry! :)

2024-04-22 05:54 UTC, tchoutri commented
Regarding the PVP breaking change, @ysangkok would I love to hear your rationale, this isn't immediately clear to me why it would be such a change.

2024-04-22 13:22 UTC, ysangkok commented
Oh you're right @tchoutri , it's not a breaking change according to the PVP flow chart to only add constructors/functions/non-orphan instances. And I suppose a pattern is like a constructor.

2024-04-22 14:18 UTC, tchoutri commented
So, in my book, adding a (public) constructor can lead to breakages when consumers do total case matches on the value. Patterns are less prone to provoke breakages when added.

2024-04-24 10:43 UTC, tchoutri requested changes
Please write a changelog.d entry. :)

2024-04-24 10:46 UTC, tchoutri commented
> I guess it _could_ be a breaking change, if some existing set of pattern synonyms were declared `COMPLETE` and a new pattern synonym were added to that set. That would be analogous to adding a "real" constructor to a datatype. But this is not the case here.

yep, that's not our case here :)

2024-04-24 18:52 UTC, tchoutri approved these changes

2024-04-24 19:28 UTC, merged